### ISSUE TITLE
yobot启动时报错

### ISSUE THREAD

**Issue by xu040633** [eggggi/yobot_remix#110]
[2024-03-18 14:43:50,394 nonebot] ERROR: route() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/qqbot/HoshinoBot/hoshino/modules/yobot/yobot_remix/__init__.py", line 1, in <module>
    from .src.client import nonebot_plugin
  File "/qqbot/HoshinoBot/hoshino/modules/yobot/yobot_remix/src/client/nonebot_plugin.py", line 44, in <module>
    bot = Yobot(
  File "/qqbot/HoshinoBot/hoshino/modules/yobot/yobot_remix/src/client/yobot.py", line 269, in __init__
    p.register_routes(quart_app)
  File "/qqbot/HoshinoBot/hoshino/modules/yobot/yobot_remix/src/client/ybplugins/homepage.py", line 19, in register_routes
    @app.route(self.public_basepath, ["GET"])
  File "/usr/local/lib/python3.8/dist-packages/flask/sansio/scaffold.py", line 46, in wrapper_func
    return f(self, *args, **kwargs)
TypeError: route() takes 2 positional arguments but 3 were given

**Comment by Momona0v0** [comment]
题外话：原来可以把它当做hoshino的插件直接装进modules使用的吗？需要调整什么东西吗？
