### ISSUE TITLE
无法运行yobotg.sh文件

### ISSUE THREAD

**Issue by Mercury-Lamp** [eggggi/yobot_remix#30]
在运行sh yobotg.sh后出现如下报错：
```
root@Lampe:/home/Lampe/pcrbot/yobot_remix/src/client/dist# sh yobotg.sh
Traceback (most recent call last):
  File "main.py", line 36, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "aiocqhttp/__init__.py", line 19, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "quart/__init__.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "quart/app.py", line 46, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "quart/asgi.py", line 29, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "quart/debug.py", line 6, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "jinja2/__init__.py", line 12, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "jinja2/environment.py", line 25, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "jinja2/defaults.py", line 3, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "jinja2/filters.py", line 13, in <module>
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/tmp/_MEIa1fTY0/markupsafe/__init__.pyc)
[2088] Failed to execute script 'main' due to unhandled exception!
```

搜索得知可能需要降级MarkupSafe，"Downgrade markupsafe to 2.0.1"
将MarkupSafe降级，pip3 install markupsafe==2.0.1，提示
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
werkzeug 2.2.1 requires MarkupSafe>=2.1.1, but you have markupsafe 2.0.1 which is incompatible.
```

将一些依赖依次降级后，运行sh yobotg.sh还是同样的报错，我的系统版本是Ubuntu 20.04.5 LTS，python版本是3.8.10，下面是我的依赖版本
```
Package                     Version
--------------------------- -----------
aiocqhttp                   0.6.8
aiofiles                    23.1.0
aiohttp                     3.8.4
aiosignal                   1.3.1
altgraph                    0.17.3
anyio                       3.6.2
APScheduler                 3.10.0
arrow                       0.17.0
async-timeout               4.0.2
attrs                       22.2.0
backports.zoneinfo          0.2.1
beautifulsoup4              4.11.2
blinker                     1.5
certifi                     2022.12.7
charset-normalizer          3.0.1
click                       8.1.3
expiringdict                1.2.2
feedparser                  5.2.1
frozenlist                  1.3.3
h11                         0.14.0
h2                          4.1.0
hpack                       4.0.0
httpcore                    0.16.3
httpx                       0.23.3
Hypercorn                   0.5.4
hyperframe                  6.0.1
idna                        3.4
importlib-metadata          6.0.0
itsdangerous                2.1.2
Jinja2                      2.11.3
MarkupSafe                  2.0.1
multidict                   6.0.4
opencc-python-reimplemented 0.1.7
peewee                      3.15.4
Pillow                      7.2.0
pip                         23.0
priority                    2.0.0
pyinstaller                 5.8.0
pyinstaller-hooks-contrib   2023.0
python-dateutil             2.8.2
pytoml                      0.1.21
pytz                        2022.7.1
pytz-deprecation-shim       0.1.0.post0
Quart                       0.6.15
requests                    2.28.2
rfc3986                     1.5.0
setuptools                  67.1.0
six                         1.16.0
sniffio                     1.3.0
sortedcontainers            2.4.0
soupsieve                   2.4
toml                        0.10.2
typing_extensions           4.5.0
tzdata                      2022.7
tzlocal                     4.2
urllib3                     1.26.14
Werkzeug                    2.1.2
wheel                       0.38.4
wsproto                     1.2.0
yarl                        1.8.2
zipp                        3.13.0
```

麻烦大佬有空帮我看下是什么原因，谢谢

**Comment by eggggi** [comment]
最好不要降级。建议将所有依赖都升到最新版

**Comment by Mercury-Lamp** [comment]
> 最好不要降级。建议将所有依赖都升到最新版

这边我是先在/src/client路径下使用pip3 install -r requirements.txt让它自动装的依赖，出现报错后，再进行降级，仍是一样的报错

**Comment by Mercury-Lamp** [comment]
> > 最好不要降级。建议将所有依赖都升到最新版
> 
> 这边我是先在/src/client路径下使用pip3 install -r requirements.txt让它自动装的依赖，出现报错后，再进行降级，仍是一样的报错

这个是刚装好依赖时的依赖版本，同样会有报错
```
(yobot) root@Lampe:/home/Lampe/pcrbot/yobot_remix/src/client# pip list
Package                     Version
--------------------------- -----------
aiocqhttp                   1.4.3
aiofiles                    23.1.0
aiohttp                     3.8.4
aiosignal                   1.3.1
anyio                       3.6.2
APScheduler                 3.10.0
arrow                       0.17.0
async-timeout               4.0.2
attrs                       22.2.0
backports.zoneinfo          0.2.1
beautifulsoup4              4.11.2
blinker                     1.5
certifi                     2022.12.7
charset-normalizer          3.0.1
click                       8.1.3
expiringdict                1.2.2
feedparser                  5.2.1
frozenlist                  1.3.3
h11                         0.14.0
h2                          4.1.0
hpack                       4.0.0
httpcore                    0.16.3
httpx                       0.23.3
hypercorn                   0.14.3
hyperframe                  6.0.1
idna                        3.4
importlib-metadata          6.0.0
itsdangerous                2.1.2
Jinja2                      2.11.3
MarkupSafe                  2.1.2
multidict                   6.0.4
opencc-python-reimplemented 0.1.7
peewee                      3.15.4
Pillow                      7.2.0
pip                         23.0
priority                    2.0.0
python-dateutil             2.8.2
pytz                        2022.7.1
pytz-deprecation-shim       0.1.0.post0
quart                       0.18.3
requests                    2.28.2
rfc3986                     1.5.0
setuptools                  67.1.0
six                         1.16.0
sniffio                     1.3.0
soupsieve                   2.4
toml                        0.10.2
tzdata                      2022.7
tzlocal                     4.2
urllib3                     1.26.14
Werkzeug                    2.2.3
wheel                       0.38.4
wsproto                     1.2.0
yarl                        1.8.2
zipp                        3.13.0
```

**Comment by eggggi** [comment]
我更新了requirements.txt，可以看下这个[commit](https://github.com/eggggi/yobot_remix/commit/14d81e2df975918300a9d8aa753fa972d904c8c4)

**Comment by Mercury-Lamp** [comment]
> 我更新了requirements.txt，可以看下这个[commeit](https://github.com/eggggi/yobot_remix/commit/14d81e2df975918300a9d8aa753fa972d904c8c4)

谢谢大佬，用这个新的依赖版本可以正常运行了。
