### ISSUE TITLE
关于挂树留言功能

### ISSUE THREAD

**Issue by ryuka-dev** [eggggi/yobot_remix#34]
在原版yobot中，`挂树`之后`查树`是会显示留言的，这一功能大多应该是用于合刀。
而大佬的魔改版好像只能通过`状态`指令来查树，而且不会显示留言。
在翻看了代码和数据库之后发现挂树并留言后留言信息是会**正常读取并保存**的，本蒟蒻尝试希望能让`状态`正常输出留言但却一直都无法正常运行。
`src\client\ybplugins\clan_battle\components\realize.py`大概是在这里修改吧？
```
                        #1175行
			if info['tree']:
				temp_msg += ', 已挂树'
			if info['msg']:
				temp_msg += info['msg']
			msg.append(temp_msg)
		msg.append('--------------------')
```
添加了如上的msg，但完全无法运行，希望大佬能解惑！

**Comment by eggggi** [comment]
这样加可以呀。
虽然记录了留言但是我还没想好怎么表现就一直鸽着了0.0，直接放在`状态`里再加上`报伤害`这些会显得很长。晚点我把`查树`命令加回去吧。
合刀的时候我建议用`报伤害`命令

**Comment by ryuka-dev** [comment]
把查树指令加回来也是可以的！
感谢回复！

**Comment by ryuka-dev** [comment]
啊 我在提Issues的时候忘记附上修改后的报错了
我又测试了一下，如此修改后会发生如下的报错：
```
[root@VM-4-15-centos client]# sh yobotg.sh 
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    import yobot
  File "/www/BOT/Yobot/yobot_remix-stable/src/client/yobot.py", line 27, in <module>
    from ybplugins import (clan_battle, homepage,
  File "/www/BOT/Yobot/yobot_remix-stable/src/client/ybplugins/clan_battle/__init__.py", line 1, in <module>
    from .battle import ClanBattle
  File "/www/BOT/Yobot/yobot_remix-stable/src/client/ybplugins/clan_battle/battle.py", line 8, in <module>
    from .components.realize import *
  File "/www/BOT/Yobot/yobot_remix-stable/src/client/ybplugins/clan_battle/components/realize.py", line 1178
    temp_msg += info['msg']
                          ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by eggggi** [comment]
emmmm，翻译一下inconsistent use of tabs and spaces in indentation

**Comment by ryuka-dev** [comment]
厚礼蟹 私密马赛
没怎么学过python，还以为是别的地方有什么问题
已经不会报错了 十分感谢

**Comment by eggggi** [comment]
挂树留言已实现，这个issues就关闭啦
