### ISSUE TITLE
作为插件运行的时候报错

### ISSUE THREAD

**Issue by xu040633** [eggggi/yobot_remix#38]
[2023-04-06 19:24:16,270 nonebot] ERROR: Failed to import "hoshino.modules.yobot.yobot", error: Expecting value: line 5 column 20 (char 86)
[2023-04-06 19:24:16,270 nonebot] ERROR: Expecting value: line 5 column 20 (char 86)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 274, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\xcw\xcwbot\HoshinoBot\hoshino\modules\yobot\yobot\__init__.py", line 1, in <module>
    from .src.client import nonebot_plugin
  File "C:\xcw\xcwbot\HoshinoBot\hoshino\modules\yobot\yobot\src\client\nonebot_plugin.py", line 44, in <module>
    bot = Yobot(
  File "C:\xcw\xcwbot\HoshinoBot\hoshino\modules\yobot\yobot\src\client\yobot.py", line 106, in __init__
    cfg = json.load(config_file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 20 (char 86)

**Comment by eggggi** [comment]
有把原来的yobot_config.json删掉吗

**Comment by xu040633** [comment]
> 有把原来的yobot_config.json删掉吗
删掉了以后解决了

**Comment by xu040633** [comment]
> 有把原来的yobot_config.json删掉吗

yobotdata文件夹删掉后解决了

**Comment by eggggi** [comment]
\_(:з)∠)_
