### ISSUE TITLE
插件启动报错，找不到yobot_data这个文件夹

### ISSUE THREAD

**Issue by cmdhb** [eggggi/yobot_remix#48]
这个应该是启动时自动生成的吧？
以下是报错

[2023-04-08 23:29:05,377 nonebot] ERROR: Failed to import and load "hoshino.modules.yobot.yobot", error: [Errno 2] No such file or directory: '/root/pcrbot/HoshinoBot/hoshino/modules/yobot/yobot/src/client/ybplugins/clan_battle/components/../../../yobot_data/user_profile'
[2023-04-08 23:29:05,378 nonebot] ERROR: [Errno 2] No such file or directory: '/root/pcrbot/HoshinoBot/hoshino/modules/yobot/yobot/src/client/ybplugins/clan_battle/components/../../../yobot_data/user_profile'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/pcrbot/HoshinoBot/hoshino/modules/yobot/yobot/__init__.py", line 1, in <module>
    from .src.client import nonebot_plugin
  File "/root/pcrbot/HoshinoBot/hoshino/modules/yobot/yobot/src/client/nonebot_plugin.py", line 30, in <module>
    from .yobot import Yobot
  File "/root/pcrbot/HoshinoBot/hoshino/modules/yobot/yobot/src/client/yobot.py", line 22, in <module>
    from .ybplugins import (clan_battle, homepage,
  File "/root/pcrbot/HoshinoBot/hoshino/modules/yobot/yobot/src/client/ybplugins/clan_battle/__init__.py", line 1, in <module>
    from .battle import ClanBattle
  File "/root/pcrbot/HoshinoBot/hoshino/modules/yobot/yobot/src/client/ybplugins/clan_battle/battle.py", line 6, in <module>
    from .components.kernel import init, execute, jobs, match
  File "/root/pcrbot/HoshinoBot/hoshino/modules/yobot/yobot/src/client/ybplugins/clan_battle/components/kernel.py", line 15, in <module>
    from .image_engine import download_missing_user_profile
  File "/root/pcrbot/HoshinoBot/hoshino/modules/yobot/yobot/src/client/ybplugins/clan_battle/components/image_engine.py", line 18, in <module>
    USER_HEADERS_PATH.mkdir()
  File "/usr/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/root/pcrbot/HoshinoBot/hoshino/modules/yobot/yobot/src/client/ybplugins/clan_battle/components/../../../yobot_data/user_profile'

**Comment by eggggi** [comment]
把原来的yobot_data文件夹删了就行了

**Comment by eggggi** [comment]
oh等下，貌似这个不太对

**Comment by cmdhb** [comment]
找不到yobot_data这个文件夹，好像没有生成

**Comment by eggggi** [comment]
修复了 https://github.com/eggggi/yobot_remix/commit/9322a90645235539e4d8006a1281cfb8636f8df5

**Comment by cmdhb** [comment]
大佬神速，可以了
