### ISSUE TITLE
建议添加IPv6的支持

### ISSUE THREAD

**Issue by liyk123** [eggggi/yobot_remix#76]
这也是之前的yobot的遗留问题了，如果用IPv6登录的话会报错
``` python
stderr: [2023-04-24 08:56:09,989] ERROR in app: Exception on request GET /login/
stderr: Traceback (most recent call last):
stderr:   File "/usr/local/lib/python3.8/site-packages/quart/app.py", line 1650, in handle_request
stderr:     return await self.full_dispatch_request(request_context)
stderr:   File "/usr/local/lib/python3.8/site-packages/quart/app.py", line 1675, in full_dispatch_request
stderr:     result = await self.handle_user_exception(error)
stderr:   File "/usr/local/lib/python3.8/site-packages/quart/app.py", line 1107, in handle_user_exception
stderr:     raise error
stderr:   File "/usr/local/lib/python3.8/site-packages/quart/app.py", line 1673, in full_dispatch_request
stderr:     result = await self.dispatch_request(request_context)
stderr:   File "/usr/local/lib/python3.8/site-packages/quart/app.py", line 1718, in dispatch_request
stderr:     return await self.ensure_async(handler)(**request_.view_args)
stderr:   File "/yobot/ybplugins/login.py", line 353, in yobot_login
stderr:     user = self._recall_from_cookie(auth_cookie)
stderr:   File "/yobot/ybplugins/login.py", line 267, in _recall_from_cookie
stderr:     userlogin.save()
stderr:   File "/usr/local/lib/python3.8/site-packages/peewee.py", line 6532, in save
stderr:     rows = self.update(**field_dict).where(self._pk_expr()).execute()
stderr:   File "/usr/local/lib/python3.8/site-packages/peewee.py", line 1898, in inner
stderr:     return method(self, database, *args, **kwargs)
stderr:   File "/usr/local/lib/python3.8/site-packages/peewee.py", line 1969, in execute
stderr:     return self._execute(database)
stderr:   File "/usr/local/lib/python3.8/site-packages/peewee.py", line 2465, in _execute
stderr:     cursor = database.execute(self)
stderr:   File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3141, in execute
stderr:     sql, params = ctx.sql(query).query()
stderr:   File "/usr/local/lib/python3.8/site-packages/peewee.py", line 608, in sql
stderr:     return obj.__sql__(self)
stderr:   File "/usr/local/lib/python3.8/site-packages/peewee.py", line 2518, in __sql__
stderr:     (ctx
stderr:   File "/usr/local/lib/python3.8/site-packages/peewee.py", line 608, in sql
stderr:     return obj.__sql__(self)
stderr:   File "/usr/local/lib/python3.8/site-packages/peewee.py", line 1764, in __sql__
stderr:     ctx.sql(self.nodes[n_nodes - 1])
stderr:   File "/usr/local/lib/python3.8/site-packages/peewee.py", line 608, in sql
stderr:     return obj.__sql__(self)
stderr:   File "/usr/local/lib/python3.8/site-packages/peewee.py", line 1764, in __sql__
stderr:     ctx.sql(self.nodes[n_nodes - 1])
stderr:   File "/usr/local/lib/python3.8/site-packages/peewee.py", line 608, in sql
stderr:     return obj.__sql__(self)
stderr:   File "/usr/local/lib/python3.8/site-packages/peewee.py", line 1374, in __sql__
stderr:     return ctx.value(self.value, self.converter)
stderr:   File "/usr/local/lib/python3.8/site-packages/peewee.py", line 620, in value
stderr:     value = converter(value)
stderr:   File "/usr/local/lib/python3.8/site-packages/peewee.py", line 5110, in db_value
stderr:     return struct.unpack('!I', socket.inet_aton(val))[0]
stderr: OSError: illegal IP address string passed to inet_aton
```
这年头手机的蜂窝网络自带IPv6，如果挂到带IPv6的服务器上会有这种问题发生

**Comment by eggggi** [comment]
提交了
