### ISSUE TITLE
boss尾刀报错

### ISSUE THREAD

**Issue by 964788339** [eggggi/yobot_remix#82]
1-5王是 47 47 47 46 47
尾刀4王就会报错其他不会
目前更新到最新也不行
以下是报错内容
Task exception was never retrieved
future: <Task finished name='Task-119' coro=<CQHttp._handle_event_with_response() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py:606> exception=No option '1098043137' in section: 'GROUPS'>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 789, in get
    value = d[option]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\collections\__init__.py", line 891, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\collections\__init__.py", line 883, in __missing__
    raise KeyError(key)
KeyError: '1098043137'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 608, in _handle_event_with_response
    response = await self._handle_event(payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 601, in _handle_event
    filter(lambda r: r is not None, await
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\bus.py", line 60, in emit
    results += await run_async_funcs(self._subscribers[event], *args,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\utils.py", line 40, in run_async_funcs
    results += await asyncio.gather(*coros)
  File "C:\Users\Administrator\Desktop\yobot\yobot_remix-stable\src\client\main.py", line 109, in handle_msg
    reply = await bot.proc_async(context)
  File "C:\Users\Administrator\Desktop\yobot\yobot_remix-stable\src\client\yobot.py", line 339, in proc_async
    res = pitem.execute(func_num, msg)
  File "C:\Users\Administrator\Desktop\yobot\yobot_remix-stable\src\client\ybplugins\clan_battle\components\kernel.py", line 199, in execute
    boss_status = self.challenge(group_id, user_id, True, None, behalf, is_continue,
  File "C:\Users\Administrator\Desktop\yobot\yobot_remix-stable\src\client\ybplugins\clan_battle\components\realize.py", line 695, in challenge
    subscribe_remind(self, group_id, boss_num)
  File "C:\Users\Administrator\Desktop\yobot\yobot_remix-stable\src\client\ybplugins\clan_battle\components\realize.py", line 815, in subscribe_remind
    self_id = who_am_i(group_id),
  File "C:\Users\Administrator\Desktop\yobot\yobot_remix-stable\src\client\ybplugins\clan_battle\components\multi_cq_utils.py", line 16, in who_am_i
    sid = config.get('GROUPS', str(GID))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option '1098043137' in section: 'GROUPS'
Task exception was never retrieved
future: <Task finished name='Task-135' coro=<CQHttp._handle_event_with_response() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py:606> exception=No option '1098043137' in section: 'GROUPS'>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 789, in get
    value = d[option]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\collections\__init__.py", line 891, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\collections\__init__.py", line 883, in __missing__
    raise KeyError(key)
KeyError: '1098043137'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 608, in _handle_event_with_response
    response = await self._handle_event(payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 601, in _handle_event
    filter(lambda r: r is not None, await
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\bus.py", line 60, in emit
    results += await run_async_funcs(self._subscribers[event], *args,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\utils.py", line 40, in run_async_funcs
    results += await asyncio.gather(*coros)
  File "C:\Users\Administrator\Desktop\yobot\yobot_remix-stable\src\client\main.py", line 109, in handle_msg
    reply = await bot.proc_async(context)
  File "C:\Users\Administrator\Desktop\yobot\yobot_remix-stable\src\client\yobot.py", line 339, in proc_async
    res = pitem.execute(func_num, msg)
  File "C:\Users\Administrator\Desktop\yobot\yobot_remix-stable\src\client\ybplugins\clan_battle\components\kernel.py", line 199, in execute
    boss_status = self.challenge(group_id, user_id, True, None, behalf, is_continue,
  File "C:\Users\Administrator\Desktop\yobot\yobot_remix-stable\src\client\ybplugins\clan_battle\components\realize.py", line 695, in challenge
    subscribe_remind(self, group_id, boss_num)
  File "C:\Users\Administrator\Desktop\yobot\yobot_remix-stable\src\client\ybplugins\clan_battle\components\realize.py", line 815, in subscribe_remind
    self_id = who_am_i(group_id),
  File "C:\Users\Administrator\Desktop\yobot\yobot_remix-stable\src\client\ybplugins\clan_battle\components\multi_cq_utils.py", line 16, in who_am_i
    sid = config.get('GROUPS', str(GID))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option '1098043137' in section: 'GROUPS'

**Comment by eggggi** [comment]
发送`手动添加群记录`试试
